### ISSUE TITLE
github.com/honestbee/jobq is unlicensed

### ISSUE THREAD

**Issue by emosbaugh** [longhorn/backupstore#100]
Although longhorn has a generous license it seems that one of its dependencies github.com/honestbee/jobq is unlicensed making it difficult to use.

Hopefully the author will respond here https://github.com/honestbee/jobq/issues/4

**Comment by innobead** [comment]
resolved by https://github.com/longhorn/backupstore/commit/8fe76fd20a32451c78eeb34833a52761c357dbf8

cc @ChanYiLin
